### ISSUE TITLE
Deletes Items When Dying

### ISSUE THREAD

**Issue by IAmSneak** [kyrptonaught/upgradeded-e-chests#3]
After death, the items in the lower half of the spatial e-chest get deleted.

1.16.4 server
0.32.5 fabric api
1.0.0 upgraded echests

Steps to reproduce:
1) Fill spatial e-chest with items
2) Die
3) Bottom 3 rows in spatial e-chest are empty

**Comment by kyrptonaught** [comment]
I'm amazed I forgot to check for this, and also amazed it took this long to pop up.

Thanks for the report. Will investigate

**Comment by kyrptonaught** [comment]
This has been fixed in 1.0.1
